RUN set -xeu && curl -L -o /usr/local/bin/lagoon https://github.com/uselagoon/lagoon-cli/releases/download/v0.19.0/lagoon-cli-v0.19.0-linux-arm64 && chmod +x /usr/local/bin/lagoon && ls -l /usr/local/bin/lagoon
RUN curl -L -o /usr/local/bin/lagoon-sync https://github.com/uselagoon/lagoon-sync/releases/download/v0.7.1/lagoon-sync_0.7.1_linux_arm64 && chmod +x /usr/local/bin/lagoon-sync && ls -l /usr/local/bin/lagoon-sync
ADD dotlagoon.yml /home/${username}/.lagoon.yml
RUN chown ${username}:${username} /home/${username}/.lagoon.yml && chmod ug+rw /home/${username}/.lagoon.yml
