name: amazeeio-ddev
type: drupal10
docroot: web
php_version: "8.1"
webserver_type: nginx-fpm
database:
    type: mariadb
    version: "10.4"
web_environment:
    - LAGOON=ddev
    - LAGOON_ENVIRONMENT=webinar
    - LAGOON_PROJECT=amazeeio-ddev
